[metadata]
name = "SIRS simulation example"
description = "Example of an SIRS model simulation"
filename = "sirs-simulation.toml"
date = "2023-08-22"


[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"

[time]
start = 0.0
until = 730.0
steps_per_unit = 1
summaries_per_unit = 1

[observations.I]
# model = "sirs_model.NoisyStateObservation"
model = "sirs_model.NegativeBinomailObservation"

[prior]
S = { name = "constant", args.value = 99998 }
I = { name = "constant", args.value = 2.0 }
R = { name = "constant", args.value = 0.0 }
betaCoef = { name = "constant", args.value = 2.0 } #~2/7
gammaCoef = { name = "constant", args.value = 1.0} #~1/7
omegaCoef = { name = "constant", args.value = 1.0 } #~1/365
kappaCoef = { name = "constant", args.value = 85 } #~1/365*18
muCoef = { name = "constant", args.value = 85 } #~1/365*18

# if no intervention, set the time greater than the end of the simulation
intervention_time = { name = "constant", args.value = 1000 }
intervention_magnitude = { name = "constant", args.value = 1.0}

[scenario.simulation]
simulation_name = "ODE style process"
components.model = "sirs_model.SIRS_JSF"
# components.model = "sirs_model.SIRS_ODE"
# observations.I.model = "sirs_model.GaussianStateObservation"
num_replicates = 1

file = "outputs/sirs-observations.ssv"
plot_path = "outputs/simulation-jsf.png"

# [scenario.simulation3]
# simulation_name = "CTMC style process"
# components.model = "sis_model.SIS_CTMC"
# observations.I.model = "sis_model.UniformObservation"
# num_replicates = 100
# file = "out/simu-ctmc-sis-observations.ssv"
# plot_path = "out/simulation-ctmc.png"

# [scenario.simulation4]
# simulation_name = "Hybrid style process"
# components.model = "sis_model.SIS_Hybrid"
# num_replicates = 100
# file = "out/simu-hybrid-sis-observations.ssv"
# plot_path = "out/simulation-hybrid.png"

[filter]
particles = 10
prng_seed = 4
history_window = -1