#+title: Jump-Switch-Flow
#+author: Dr Domenic Germano

This is the code repo to accompany the original JSF paper

The code found in the directory =SimpleODEModel= is used to describe a
simple Lotka-Volterra model. This illistrates how JSF can be used in a
simple system, and demonstrates the basic principles of JSF.

The code found in the directory [[file:./SIRS_Results/particle-filter-example-sirs/readme.org][=SIRS_Results=]] performs a simulation
study of the SIRS model, and demonstrates how JSF can be used to study
a more complex system. Specifically, we show how JSF is computaionally
more efficient than the gold standard Doob-Gillespie algorithm, and
also fixed step Tao-leaping algorithm. We then show how JSF can be
couple with [[https://pypfilt.readthedocs.io/en/latest/index.html][pypfilt]], a particle filter library, to perform parameter
estimation on the SIRS model.

The code found in the directory [[file:./TEIVR_Results/particle-filter-example-tiv_covid/readme.org][=TEIVR_Results=]] performs the analysis
on the TEIVR model to estimate the model parameters. Here, we estimate
viral reproduction number, and also estimate the probability of viral
clearance for each patient. The directory `map-compute-demo' performs
the R_0 estimates from the inference study.
