[metadata]
name = "tiv inference example using simulated data"
description = "Example of a TIV inference from simulated data"
author = "Alexander E. Zarebski"
date = "2023-08-28"

[components]
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"
model = "src.tiv.TIV_ODE"

[time]
start = 0.0
until = 8.0
steps_per_unit = 200
summaries_per_unit = 1

[observations.V]
model = "src.tiv.Gaussian"
scale = 1.5

[prior]
T0 = { name = "constant", args.value = 4E8 }
I0 = { name = "constant", args.value = 0.0 }

[scenario.simulation]
# Some helpful conversions
# log(1.0E-6) = -13.8
# log(1.0E-3) = -6.91
# log(1.0E-2) = -4.61
# log(1.0E0) = 0.00
# log(1.0E1) = 2.30
# prior.V0 = { name = "constant", args.value = 3.5E-1 }
prior.lnV0 = { name = "constant", args.value = -1.05 }
prior.beta = { name = "constant", args.value = 3.4E-5 }
prior.p = { name = "constant", args.value = 7.9E-3 }
prior.c = { name = "constant", args.value = 3.3 }
prior.gamma = { name = "constant", args.value = 3.4 }
sim_output_file = "out/simulated-data-for-inference.ssv"

[scenario.inference]
# Some helpful conversions
# log(1.0E-6) = -13.8
# log(1.0E-3) = -6.91
# log(1.0E-2) = -4.61
# log(1.0E0) = 0.00
# log(1.0E1) = 2.30
prior.lnV0 = { name = "uniform", args.loc = -6.91, args.scale = 6.91 }
prior.beta = { name = "uniform", args.loc = 1.0E-6, args.scale = 1.0E-4 }
prior.p = { name = "uniform", args.loc = 1.0E-3, args.scale = 1.0E-2 }
prior.c = { name = "uniform", args.loc = 1.0, args.scale = 1.0E1 }
prior.gamma = { name = "uniform", args.loc = 1.0, args.scale = 1.0E1 }
summary.tables.model_cints.component = "pypfilt.summary.ModelCIs"
summary.tables.model_cints.credible_intervals = [10, 20, 30, 40, 50, 60, 70, 80, 90]
summary.tables.forecasts.component = "pypfilt.summary.PredictiveCIs"
summary.tables.forecasts.credible_intervals = [10, 20, 30, 40, 50, 60, 70, 80, 90]

[filter]
particles = 20000
prng_seed = 1
history_window = -1
resample.threshold = 0.25
regularisation.enabled = true

[filter.regularisation.bounds]
lnV0 = { min = -10.0, max = 10.0 }
beta = { min = 0.0, max = 1E10 }
p = { min = 0.0, max = 1E10 }
c = { min = 0.0, max = 1E10 }
gamma = { min = 0.0, max = 1E10 }